// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD35e-JXK7O11p_9ww5Dx_8at56GfhO5U',
    appId: '1:144557833666:web:201ce17283346f96fd2a5b',
    messagingSenderId: '144557833666',
    projectId: 'trc-customsindore',
    authDomain: 'trc-customsindore.firebaseapp.com',
    storageBucket: 'trc-customsindore.firebasestorage.app',
    measurementId: 'G-51JMRZBBJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxK-UO34VFblZm-5-6Qj01bIqQ0n6GfKo',
    appId: '1:144557833666:android:1d4ce52db0cfcd25fd2a5b',
    messagingSenderId: '144557833666',
    projectId: 'trc-customsindore',
    storageBucket: 'trc-customsindore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuqQcIYDGYbnNqbdJbSIGBmtQxxqxLJ2A',
    appId: '1:144557833666:ios:85f70feec46ba939fd2a5b',
    messagingSenderId: '144557833666',
    projectId: 'trc-customsindore',
    storageBucket: 'trc-customsindore.firebasestorage.app',
    iosBundleId: 'com.example.importLookup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuqQcIYDGYbnNqbdJbSIGBmtQxxqxLJ2A',
    appId: '1:144557833666:ios:85f70feec46ba939fd2a5b',
    messagingSenderId: '144557833666',
    projectId: 'trc-customsindore',
    storageBucket: 'trc-customsindore.firebasestorage.app',
    iosBundleId: 'com.example.importLookup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD35e-JXK7O11p_9ww5Dx_8at56GfhO5U',
    appId: '1:144557833666:web:1c879ea53218f437fd2a5b',
    messagingSenderId: '144557833666',
    projectId: 'trc-customsindore',
    authDomain: 'trc-customsindore.firebaseapp.com',
    storageBucket: 'trc-customsindore.firebasestorage.app',
    measurementId: 'G-N92SYSNFPK',
  );

}